# Generated by Django 4.0.5 on 2022-11-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
